doc/rosenpass.1

This commit adds a manual page for the rosenpass(1) utility. Currently, it's content is mostly a replica of rosenpass's built-in help.

man: add rosenpass.1

---

Cargo.lock
Cargo.toml
build.rs
flake.nix
src/main.rs

This commit invokes the `man(1)` command with the rosenpass manual page, when invoking `help`.
In the future, we should handle the case, that a rosenpass manual page is not installed, somewhat better. My idea would be to render the manual page to an HTML version regularly and provide a link to it inside the error message.

invoke `man(1)` when requesting help

---

.github/workflows/nix.yaml
.github/workflows/qc.yaml
.github/workflows/release.yaml
src/cli.rs

These are cross compilation static build jobs
which are nice to have but non-essential.

fix: Disable broken CI jobs

---

flake.nix

This commit reverts the CMake change done in #90, as it broke the invocation of `cargo build`.
While this might be considered as a hotfix, it at least fixes building through `cargo build` and, in my opinion more importantly, makes it possible to run unit tests through `cargo test` again.

fix devshell bug introduced in #90

---

.ci/gen-workflow-files.nu
.github/workflows/nix.yaml
.github/workflows/qc.yaml
.github/workflows/release.yaml

This commit adds two new jobs. One checks that `cargo test` runs through, and second one checking that `cargo test` inside the nix devshell runs through as well.
fixes #98

add smoke test for devshell and test without nix

---

rp

If currently no IP address, only on IPv6 is listen by default. This commit would make it listen dual-stack - i.e. IPv4 and IPv6 - by default.

rp: Defaults to dual-stack

---

src/cli.rs

This commit re-introduces a static and pre-compiled version of the manual page back into the source code, in case that an installed version cannot be found on the host system.

cli: include a static compiled manual page

---

src/cli.rs

This commit moves the `StaticKEM::keygen` call out of an `unsafe` call, because the function is not unsafe.

cli: Move `StaticKEM::keygen` out of `unsafe`

---

Cargo.lock
Cargo.toml
src/protocol.rs

This commit ensures that the call to `StaticKEM::keygen` has a stack of 16MB.
Especially on Darwin system, this commit is necessary in order to prevent a stack overflow, as this system only provides stack sizes of roughly 500KB which is way to small for a Classic McEliece key.
Fixes #118

test: Ensure 8MiB of stack size for key generation

---

src/config.rs

Otherwise, omitting `extra_params` in the configuration file will result in a `WireGuard` configuration object of `None`, even though not specifying `extra_params` is sane.
See also https://github.com/NixOS/nixpkgs/pull/254813#issuecomment-1738738224
The code I used to test this (which changes more than just one line) is at https://github.com/rosenpass/rosenpass/compare/main...ngi-nix:rosenpass:config ... If you want me to add the additional method to parse a configuration from a string and the test to this PR, please tell me. Thanks.

config: Default `WireGuard::extra_params` to empty `Vec`

---

src/app_server.rs

This commit replaces an `is_ok()` call with a call to `if let`, thereby fixing a clippy warning.

app_server: Replace `is_ok()` by `if let`

---

fuzzing/fuzz_targets/handle_msg.rs
fuzzing/fuzz_targets/mceliece_encaps.rs

When fuzzing we are interested in what happens inside the target function not necessarily what it returns. Functions returning errors with bogus input in generally desired behaviour.

Remove unwrap from fuzz targets that return errors

---

Cargo.toml
ciphers/Cargo.toml
constant-time/Cargo.toml
fuzzing/Cargo.toml
rosenpass/Cargo.toml
sodium/Cargo.toml
to/Cargo.toml
util/Cargo.toml

Move external dependencies to the workspace cargo.toml file
/claim #178 
fixes #178

feat: Move dependencies into the workspace

---

Cargo.lock
Cargo.toml
secret-memory/src/secret.rs
sodium/Cargo.toml
sodium/src/alloc/allocator.rs
sodium/src/alloc/mod.rs
sodium/src/lib.rs

This exposes the libsodium allocation API as an allocator and uses that together with allocator-api2's Box and Vec to implement the secret pool.
This brings the number of unsafe blocks needed to implement this down to two from six.

Improve the safety of the secret storage mechanism

---

papers/tex/template-rosenpass.tex

just a small adjustment in the rosenpass LaTeX template – as requested

fix output of authorlist to support unlimited authors

---

flake.nix

Fixes #65. I checked with `pdffonts` that the whitepaper still has all fonts embedded.

fix: remove OSFONTDIR var from whitepaper build

---

rosenpass/src/cli.rs
rosenpass/src/main.rs

Added deprecated keygen command, based on old usage.
```
rosenpass keygen \
private-key mykey/pqsk \
public-key mykey/pqpk
```
And old code:
```
-/// Generate a keypair
-pub fn cmd_keygen(mut args: ArgsWalker) -> Result<()> {
-    let mut sf: Option<String> = None;
-    let mut pf: Option<String> = None;
-
-    // Arg parsing
-    loop {
-        match args.next() {
-            Some("private-key") => args.opt(&mut sf)?,
-            Some("public-key") => args.opt(&mut pf)?,
-            Some(opt) => bail_usage!(&args, "Unknown option `{}`", opt),
-            None => break,
-        };
-    }
-
-    mandatory_opt!(&args, sf, "private-key");
-    mandatory_opt!(&args, pf, "private-key");
-
-    // Cmd
-    let (mut ssk, mut spk) = (SSk::random(), SPk::random());
-    unsafe {
- …
```

Add backwards compatibility for keygen command

---

.github/workflows/qc.yaml
format_rust_code.sh
to/README.md

Summary: 
Added format_rust_code.sh file that uses rustfmt tool on rust code in fences.
to check document formatting run: run bash format_rust_code.sh --mode check
to fix run : run bash format_rust_code.sh --mode fix
modifie qc.yml: To run format_rust_code.sh
Issue References:
Fixes: #156 
/claim #156

Enforce code style on doc comments #156

---

rosenpass/src/cli.rs

Happy for the chance to do a quick grammar pr. Feedback welcome.

Fixed grammatical typo in 'cli.rs'. To resolve issue #236.

---

rosenpass/src/cli.rs
rosenpass/src/main.rs

implements CLI arguments `--verbose`, `--quiet` and `--log-level LEVEL` as required by #92 
/claim #92 
arguments are mutually exclusive:
```text
cargo run --release -- -q -v keygen
[...]
Finished `release` profile [optimized] target(s) in 0.11s
Running `/home/user/rosenpass/target/release/rosenpass -q -v keygen`
error: the argument '--quiet' cannot be used with '--verbose'
Usage: rosenpass --quiet <COMMAND>
For more information, try '--help'.
```
Any of by Rust's [`log::LevelFilter`](https://docs.rs/log/latest/log/enum.LevelFilter.html) are supported in lowercase and uppercase.
If no log level filter is specified via the CLI, the program will behave like it did prior to this PR: it will use the `env_logger` crate to read the level from the environment or default. I did exactly #92 and …

resolve #92: add CLI argument to specify log level filter

---

Cargo.lock
Cargo.toml
rosenpass/Cargo.toml
rosenpass/src/config.rs

Instead use the `home` create.

config: drop deprecated std::env::home_dir()

---

flake.nix

Upstream fix #216904 got fixed to remove the extra overlay.

flake: drop overlay due to upstream fix

---

.github/workflows/qc.yaml
constant-time/src/compare.rs

The compare function should do a little-endian comparision, therefore copy the code from quinier/memsec and don't revert the loop, tada, le.

constant-time: add secure memcmp_le function

---

.github/workflows/qc.yaml

This stops fuzzing to run which takes forever and breaks the CI.

bench: exclude rosenpass-fuzzing

---

rosenpass/src/app_server.rs
rosenpass/src/cli.rs
rosenpass/src/config.rs
secret-memory/src/file.rs
secret-memory/src/secret.rs
util/src/file.rs

When creating secret keys or use the out file feature, the material shouldn't be readble to everyone by default.
Fix: #260

proper permission for secrets aka 0o600

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This PR sets up a `.devcontaner` configuration to enable the use of any tools built on devcontainers in development. It sets the dev environment up based on the repo's `flake.nix`, using the [`nix-devcontainer`](https://github.com/xtruder/nix-devcontainer) project.

Add .devcontainer configuration

---

Cargo.lock
Cargo.toml
rosenpass/src/app_server.rs
rosenpass/src/cli.rs
rp/Cargo.toml
rp/src/exchange.rs
rp/src/key.rs
secret-memory/Cargo.toml
secret-memory/src/public.rs
secret-memory/src/secret.rs
util/Cargo.toml
util/src/b64.rs
util/src/file.rs

Investigating #261 , I found `base64`'s `Encoder` and `Decoder` implements the `Read` and `Write` traits. However, they use their own built in buffer, which can store unprotected copies of secrets.
The [`base64ct` crate](https://docs.rs/base64ct/latest/base64ct/) is built  and used for cryptographic applications, and has no-std support (stack only) and minimal buffering AFAICT. This allows us to use `Secret` and avoid intermediate buffers that are on the heap or copies stored elsewhere in crates structs.

Change base64 to base64ct crate

---

.github/workflows/dependent-issues.yml

Dependent issues needs permissions to access issues, PRs, etc.

chore: Add write permissions in dependent-issues workflow

---

.github/workflows/dependent-issues.yml
Cargo.lock
Cargo.toml
rosenpass/Cargo.toml
rosenpass/src/app_server.rs
rosenpass/src/cli.rs
rosenpass/src/config.rs
rosenpass/src/protocol.rs
rosenpass/tests/integration_test.rs
rp/Cargo.toml
rp/src/cli.rs
rp/src/exchange.rs
secret-memory/src/public.rs
secret-memory/src/secret.rs
util/src/b64.rs
wireguard-broker/Cargo.toml
wireguard-broker/src/api/client.rs
wireguard-broker/src/api/config.rs
wireguard-broker/src/api/mod.rs
wireguard-broker/src/api/server.rs
wireguard-broker/src/bin/priviledged.rs
wireguard-broker/src/brokers/mio_client.rs
wireguard-broker/src/brokers/mod.rs
wireguard-broker/src/brokers/native_unix.rs
wireguard-broker/src/brokers/netlink.rs
wireguard-broker/src/lib.rs
wireguard-broker/tests/integration.rs

Dynamically dispatch WireguardBrokerMio trait in AppServer. Also allows for mio event registration and poll processing, similar to dev/broker-architecture branch
Tested basic setup of connections between two devices

feat(rosenpass): Add wireguard-broker interface in AppServer

---

rosenpass/src/app_server.rs

Right now a warning message is logged if no Wireguard peer is defined. This is misleading in cases where the outfile is used instead.

Warn only if neither peer nor outfile is defined

---

rosenpass/src/protocol.rs

Change handle_init_conf to return to instruct key exchange on encountering new biscuit_no for peer
Fixes #327

fix(rosenpass): Fix duplicate key issue

---

.github/workflows/qc.yaml
cipher-traits/readme.md
flake.nix
readme.md

chore: Remove libsodium references in nix flake, ci

---

.github/workflows/qc.yaml
Cargo.lock
Cargo.toml
wireguard-broker/Cargo.toml
wireguard-broker/src/bin/priviledged.rs
wireguard-broker/src/bin/socket_handler.rs
wireguard-broker/src/brokers/mod.rs
wireguard-broker/src/brokers/netlink.rs

Added a runner for the cargo test to run on MacOS 13 (x86-64 architecture, not ARM)

Add cargo-test runner for macos x86-64

---

fuzz/fuzz_targets/kyber_encaps.rs

This PR fixes the length of `shared_secret`, changing it from `SK_LEN` to `SHK_LEN` so that the fuzz test now passes unconditionally.
This is one of the two current CI failures on `main`. The other (a test failure during one of the Nix builds) I haven't been able to reproduce, and think is likely due to a caching issue; in particular, that test was previously failing on main but was fixed by the prior PR merge.

Fix Kyber encapsulation fuzz test shared key length to make test pass

---

rp/src/exchange.rs

drop unused import of WG_B64_LEN

---

Cargo.lock
Cargo.toml
ciphers/Cargo.toml
ciphers/src/lib.rs
ciphers/src/subtle/chacha20poly1305_ietf_libcrux.rs
ciphers/src/subtle/mod.rs
fuzz/Cargo.toml
rosenpass/Cargo.toml
rp/Cargo.toml

Libcrux is a library for formally verified implementations of cryptographic primitives. It uses multiple back ends; one of which is libjade. A cryptographic library written in the jasmin assembly language for high assurance cryptographic implementations.
To use compile with the experiment_libcrux feature enabled:
cargo build --features experiment_libcrux

feat: Experimental support for encryption using libcrux

---

rosenpass/src/protocol/protocol.rs
util/src/controlflow.rs
util/src/fd.rs
util/src/lib.rs
util/src/ord.rs
util/src/time.rs

Trigger the internal assert of owned.rs instead of writing our own. To correctly test it use `should_panic` macro.

fd/time: add tests, docs, cleanups

---

rosenpass/src/protocol/protocol.rs

There seem to be a paste typo in the docs, drop it to lower confusion.

chore: drop copy & paste doc error in protocol.rs

---

rosenpass/src/protocol/protocol.rs

Those are seconds not ms, also it's BEGIN not BEG.

docs: Correct protocol retransmission unit/vars

---

.github/workflows/nix.yaml

More than 6 hours aka failing the CI. Drop it for now and hope to have it enabled later again.

ci: Skip Nix build of aarch64 since it takes forever

---

.github/workflows/nix.yaml
.github/workflows/qc.yaml
.github/workflows/regressions.yml

Instead of running outdated CI jobs, skip them automatically.

ci: add `concurrency` option to skip in progress

---

Cargo.lock
rosenpass/Cargo.toml

The latest release left the `main` branch on 0.2.1

chore(rosenpass): Set version to 0.3.0-dev

---

.ci/boot_race/a.toml
.ci/boot_race/b.toml
.ci/boot_race/run.sh
.github/workflows/regressions.yml

If two instances start up at the same time, they end up with different keys on both ends. Test this with different delays of 2 (working), 1 (flaky) and 0 (broken) seconds.

ci: add regression test for boot race condition

---

rosenpass/src/cli.rs
rosenpass/src/config.rs
rosenpass/tests/integration_test.rs

The configuration file created via `rosenpass geo-config` now contains comments. Improve config validation and tell the user what's actually broken.

User friendlier example config creation

---

CONTRIBUTING.md

Presumably, this should match the command used in the CI workflow and not skip any features?
Edit: I mean [this one](https://github.com/rosenpass/rosenpass/blob/main/.github/workflows/qc.yaml#L135).

Add missing cargo test arguments in CONTRIBUTING.md

---

rosenpass/src/api/mio/connection.rs

Technically a breaking change... Hopefully that's not a problem here?

Rename mio.connection.shoud_close (typo in function name)

---

Cargo.lock
flake.nix
pkgs/release-package.nix
pkgs/rosenpass.nix
rp/Cargo.toml
rp/src/cli.rs
rp/src/exchange.rs
rp/src/main.rs
systemd/rosenpass.target
systemd/rosenpass@.service
systemd/rp@.service
tests/systemd/rosenpass.nix
tests/systemd/rp.nix

This PR introduces systemd unit files to simplify running `rosenpass` and`rp` with minimal setup. The workflow after these changes is like this:
1. Create configuration files, private/public keys on both server and client, and distribute them accordingly
2. Start the service using `systemctl start rp@<config-name>.service` (or respectively `rosenpass@<config-name>.service`)
3. Enjoy a post-quantum-secure encrypted connection
I tested this manually on an Ubuntu machine. The automated tests use NixOS, see next section.
To achieve the above, the following changes have been made:
- Rosenpass Unit File: 
- Added a systemd unit file for `rosenpass`
- Implemented a NixOS integration test for verification
- `rp` App: Patched the `rp` application to support configuration files
- `rp` Unit File:
- …

Introduce "High Quality" Systemd unit files for `rosenpass` and `rp`

---

Cargo.lock
Cargo.toml
rosenpass/Cargo.toml
rosenpass/src/main.rs
rosenpass/tests/api-integration-tests-api-setup.rs

Three changes:
1. We neglected to forward stderr from Rosenpass subprocess two in the API setup integration test (driveby fix)
2. Added rudimentary signal handling for program termination to rosenpass, specifically for the coverage reporting
3. Apparently std::process::Child::kill() sends SIGKILL and not SIGTERM, so our nice new signal handler was never used. Switched to a rustix based child reaper.
(2) and (3) where necessary because llvm-cov does not produce coverage when a subprocess terminates due to a default signal handler.

chore(coverage): Fix missing coverage from API integration tests

---

Cargo.lock
cipher-traits/Cargo.toml
cipher-traits/src/kem.rs

In the doctests in `kem.rs`, the actual tests that are run to verify that the KyberKem and the DummyKem actually work
are wrapped inside a function to make use of the `?`-operator. However, these functions were never called and thus the tests weren't really helpful and didn't provide proper coverage. This PR fixes this.

Fix doctests where Function is wrapped around the actual test but is never called in cipher traits

---

rosenpass/tests/integration_test.rs

Resolve a warning of unused `output` variable.
Fixes: 0745019 docs(cli): Create commented config file

chore(tests): start using unused test output

---

ciphers/src/hash_domain.rs

Following the changes in other PRs, I adopedt the style about doc-tests using the `?`-operator in the ciphers crate.

style(ciphers): improve style in doc-tests around using the the ?-operator in the ciphers crate

---

util/src/lib.rs
util/src/mio/mio.rs
util/src/mio/uds_recv_fd.rs

No function coverage yet:
* `uds_recv_fd`: `socket_mut`, which is a trivial accessor (`socket` is already covered)
* `uds_send_fd`: `flush` is a NOOP, `socket_mut` same as `socket`, `into_parts` similar to `uds_recv_fd`
Usefulness of the examples is debatable. I focused on the RECV part since SEND had decent coverage already.
---
Status: Should be ready for review/merge. I'll submit a separate PR for the `uds_send_fd` example shortly.

Add examples and docstring improvements for mio/uds_recv_fd

---

util/src/length_prefix_encoding/encoder.rs
util/src/length_prefix_encoding/mod.rs

~~Warning: Needs (a lot of) refinement. Placeholders abound.~~
---
Status: Should be ready for review/merge, pending further comments.

Add docstring examples and unit tests for the LengthPrefixEncoder module

---

coverage_report.sh

The doctest binaries can take up ~3GB for a debug build. There's no reason to waste that much disk space and copying them is slower than moving, too. They're only used by `grcov` right now, so they needn't be preserved.
---
Before:
```sh
> du -sh target
8.6G    target
```
```sh
> du -h target | sort -h | tail -n 6
3.0G    target/llvm-cov-target/debug/deps/doctestbins
3.0G    target/llvm-cov-target/doctestbins
4.6G    target/llvm-cov-target/debug/deps
5.2G    target/llvm-cov-target/debug
8.5G    target/llvm-cov-target
8.6G    target
```
After:
```sh
> du -sh target
5.6G    target
```
```sh
> du -h target | sort -h | tail -n 6
265M    target/llvm-cov-target/debug/build
3.0G    target/llvm-cov-target/debug/deps/doctestbins
4.6G    target/llvm-cov-target/debug/deps
5.2G …
```

Avoid unnecessarily copying the doctest binaries

---

coverage_report.sh

Looks like `cargo llvm-cov` doesn't clean up the entire `target/llvm-cov-target` directory tree, which means running the coverage script more than once fails as `mv` refuses to overwrite the leftover doctest binaries from a previous run.

Add a missing cleanup step to the coverage script

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2024-0402
Also updated yanked crate `critical-section`.

fix(deps): fix crate vulnerabilities

---

Cargo.lock
Cargo.toml
deny.toml
rosenpass/tests/main-fn-generates-manpages.rs
supply-chain/config.toml
util/src/fd.rs

- Had to remove the test checking for manpages to be generated for the keygen command since clap-mangen disabled creating manpages for hidden commands. https://github.com/clap-rs/clap/commit/d96cc71626c5291718b7db697d4aca2d03ef496f
- Had to pin home to the previous version because it now requires a new rust version without major version update

chore: cargo update

---

.github/workflows/docker.yaml

This is a small fix to the previous PR #582 . It now properly sets [the required permissions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions) to push the image. 
Apologies for missing this.

feat(docker): change write permission on docker build workflow to have write permission to packages

---

.github/workflows/cargo-crev-exemptions-dependabot.yml

This PR enables the github workflow that regenerates exemptions for `cargo-crev` for dependabot to push to the PR.

enable github workflow for creating crev-exemptions for dependabots to push changes to PR

---

deny.toml

error[unmaintained]: atomic-polyfill is unmaintained
┌─ /github/workspace/Cargo.lock:15:1
│
15 │ atomic-polyfill 1.0.3 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2023-0089
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0089
├ The author has archived the GitHub repository and mentions deprecation in
project's
[README](https://github.com/embassy-rs/atomic-polyfill/blob/48e55c166684f37af0b00fbee5a0809b1a2bae8e/README.md).
* [portable-atomic](https://crates.io/crates/portable-atomic) ├ Announcement: https://github.com/embassy-rs/atomic-polyfill/commit/48e55c166684f37af0b00fbee5a0809b1a2bae8e ├ Solution: No safe upgrade is available! ├ atomic-polyfill …

chore: Ignore rust advisory RUSTSEC-2023-0089

---

.github/workflows/dependent-issues.yml
.github/workflows/docker.yaml
.github/workflows/nix-mac.yaml
.github/workflows/nix.yaml
.github/workflows/qc-mac.yaml
.github/workflows/qc.yaml
.github/workflows/regenerate-cargo-vet-exemptions.yml
.github/workflows/regressions.yml
.github/workflows/supply-chain.yml

This PR changes the CI for dependabot PRs such that initially, only the exemptions for cargo vet are regenerated and pushed to the PR.
Only after that, all other workflows are triggered. This ensures that the CI result for dependabot PRs is properly presented on github.

fix: make CI workflows run after pushing excemptions for cargo-vet

---

papers/references.bib
papers/whitepaper.md

This PR adds how SHAKE256 has been introduced to rosenpass and how it interfaces with the protocol in the reference implementation.

feat(sha3+paper): add information on how SHAKE256 is used in rosenpass to the whitepaper

---

rosenpass/src/config.rs

This PR fixes the error message that is given if the secret key can not be read. Currently, it incorrectly states that the public key can not be read.

fix(rosenpass): Fix the error message if the secret key is invalid

---

Cargo.lock
Cargo.toml
rosenpass/Cargo.toml
rosenpass/benches/trace_handshake.rs
supply-chain/config.toml
util/src/trace_bench.rs

This PR cleans up the way we serialize the JSON in the trace-based protocol benchmarks. We used to do manual serialization based on writing strings, but now we use serde.

Use serde for JSON-encoding benchmark data
