rosenpass/rosenpass

Cargo.toml
flake.nix

Also just parse the `Cargo.toml` for the nix `meta` attribute.

add even more metadata to Cargo.toml

---

.github/workflows/nix.yaml

This pull request introduces automatic Release creation on new tags.

Automatic Release

---

papers/whitepaper.md

Ich schlage auch in Fig 4.
Comment 7:
Ensure the responder has the correct view of spki.

Lektorat für whitepaper

---

src/app_server.rs

cli: reap spawned wireguard child

---

flake.nix
src/protocol.rs

See the commit messages for more details.
Also see #128

Follow-ups to the stack increasements

---

Cargo.lock
flake.lock

Updates `Cargo.lock` and `flake.lock`

update lock files

---

rosenpass/src/util.rs

Simple first unit test, as doc test.

doc: Add unit test for xor_into

---

doc/rosenpass.1

doc: Add bibliography to the manual page

---

Cargo.lock
Cargo.toml
rosenpass/Cargo.toml
rosenpass/src/app_server.rs
rosenpass/src/cli.rs
util/Cargo.toml
util/src/fd.rs
util/src/lib.rs
wireguard-broker/Cargo.toml
wireguard-broker/readme.md
wireguard-broker/src/api/client.rs
wireguard-broker/src/api/mio_client.rs
wireguard-broker/src/api/mod.rs
wireguard-broker/src/api/msgs.rs
wireguard-broker/src/api/server.rs
wireguard-broker/src/bin/priviledged.rs
wireguard-broker/src/bin/socket_handler.rs
wireguard-broker/src/lib.rs
wireguard-broker/src/netlink.rs

This allows us to run with minimal priviledges in the Rosenpass process itself.
The PR is currently a draft because we need to improve the code quality to merge this…

feat: First version of broker based WireGuard PSK interface

---

analysis/03_identity_hiding.entry.mpv
analysis/crypto/kem.mpv
analysis/rosenpass/oracles.mpv
analysis/rosenpass/protocol.mpv

supersedes https://github.com/rosenpass/rosenpass/pull/199

Dev/digital phoenix/rebase

---

doc/rosenpass.1

doc: Fix keygen/gen-keys misspell

---

Cargo.lock
Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2024-0019
https://rustsec.org/advisories/RUSTSEC-2024-0006

fix: Fix crate vulnerabilities

---

.github/dependabot.yml

This checks daily for outdated cargo crates.

dependabot: add configuration

---

ciphers/src/subtle/blake2b.rs
ciphers/src/subtle/chacha20poly1305_ietf.rs
ciphers/src/subtle/xchacha20poly1305_ietf.rs
constant-time/src/memcmp.rs
rosenpass/src/app_server.rs
rosenpass/src/msgs.rs
rosenpass/src/protocol.rs
rp/src/key.rs
util/src/typenum.rs

This fixes all warnings currently issued by the clippy tool.

Clippy Fixes

---

rp/src/key.rs

Fixes #287
cc @koraa (please excuse the delay)

rp: Load WireGuard SK into secret memory

---

.github/workflows/qc.yaml
doc/check.sh

ci: Changes from #160- Invoke the mandoc linter

---

.github/codecov.yml

Disables patch code coverage reporting and increases threshold percentage for pull request reporting

chore: Add codecov configuration file

---

.github/workflows/dependent-issues.yml

Adds dependent issues GH workflow
https://github.com/marketplace/actions/dependent-issues

Dependent issues Workflow

---

rosenpass/Cargo.toml
rosenpass/src/cli.rs
rp/Cargo.toml
rp/src/main.rs

Hide memfd_secret alloc behind feature flag, till we figure out a way to correct #341

Feature flag for memfd_secret alloc

---

Cargo.lock
Cargo.toml

feat: Improved memfd-secret allocation

---

fuzz/fuzz_targets/handle_msg.rs
rosenpass/benches/handshake.rs

This PR is a hotfix for the compilation errors in the fuzz tests and benchmarks resulting from #350.

Fix CI after merge of branch introducing PublicBox

---

CONTRIBUTING.md

... or else the CI fails on all PRs

Docs: run prettier over CONTRIBUTING.md

---

rosenpass/Cargo.toml
rosenpass/src/api/api_handler.rs
rosenpass/src/api/boilerplate/byte_slice_ext.rs
rosenpass/src/api/boilerplate/message_type.rs
rosenpass/src/api/boilerplate/payload.rs
rosenpass/src/api/boilerplate/request_ref.rs
rosenpass/src/api/boilerplate/request_response.rs
rosenpass/src/api/boilerplate/response_ref.rs
rosenpass/src/api/boilerplate/server.rs
rosenpass/src/bin/gen-ipc-msg-types.rs
rosenpass/src/config.rs
rosenpass/tests/api-integration-tests-api-setup.rs
util/src/controlflow.rs
util/src/fd.rs
util/src/mio/mio.rs

Feel free to review @blipp @aparcar @pqcfox 
PR based on #392

API Feature: Adding listen sockets

---

rosenpass/src/app_server.rs

This fixes
```console
$ cargo build --package rosenpass --no-default-features
Compiling rosenpass v0.2.1 (/home/debian/devel/rosenpass/rosenpass)
error[E0433]: failed to resolve: could not find `api` in the crate root
--> rosenpass/src/app_server.rs:1212:20
|
1212 |         use crate::api::mio::MioManagerContext;
|                    ^^^ could not find `api` in the crate root
|
note: found an item that was configured out
--> rosenpass/src/lib.rs:2:9
|
2    | pub mod api;
|         ^^^
note: the item is gated behind the `experiment_api` feature
--> rosenpass/src/lib.rs:1:7
|
1    | #[cfg(feature = "experiment_api")]
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0599]: no variant or associated item named `PskBroker` found for enum `AppServerIoSource` in the current scope
--> …
```

fix(rosenpass): fix compilation without API

---

rosenpass/src/cli.rs

This commit does multiple things at once to improve the user experience:
* Always start with an upper case letter, no mixing
* Hide deprecated `keygen` command, it still works if called
* Extend and rework some documentation textx
* Drop false `log_level` text, it contains a logic error
* Wrap all documentation at 80 chars

docs(cli): Improve help text

---

to/src/lib.rs
to/src/to/beside.rs
to/src/to/condense.rs
to/src/to/dst_coercion.rs
to/src/to/to_trait.rs
to/src/to/with_destination.rs
util/src/fd.rs
util/src/io.rs
util/src/length_prefix_encoding/decoder.rs
util/src/length_prefix_encoding/encoder.rs
util/src/length_prefix_encoding/mod.rs
util/src/lib.rs
util/src/mem.rs
util/src/mio/mio.rs
util/src/mio/uds_recv_fd.rs
util/src/mio/uds_send_fd.rs
util/src/option.rs
util/src/result.rs
util/src/time.rs
util/src/typenum.rs
util/src/zerocopy/ref_maker.rs
util/src/zerocopy/zerocopy_ref_ext.rs
util/src/zerocopy/zerocopy_slice_ext.rs
util/src/zeroize/zeroized_ext.rs

This PR collects a bunch of commits to add docstrings wherever needed, later on adding automated testing, too.

Fix docstring warnings

---

ciphers/src/hash_domain.rs
ciphers/src/lib.rs
flake.nix
papers/whitepaper.md
rosenpass/src/msgs.rs
rosenpass/src/protocol/protocol.rs
util/src/time.rs

Hash based retransmission

---

util/src/length_prefix_encoding/decoder.rs

docs(util): add more tests and example to complete coverage

docs(util): fix doc reference in decoder.rs

---

wireguard-broker/src/api/client.rs
wireguard-broker/src/api/config.rs
wireguard-broker/src/api/mod.rs
wireguard-broker/src/api/msgs.rs
wireguard-broker/src/api/server.rs
wireguard-broker/src/bin/priviledged.rs
wireguard-broker/src/bin/socket_handler.rs
wireguard-broker/src/brokers/mio_client.rs
wireguard-broker/src/brokers/native_unix.rs
wireguard-broker/src/brokers/netlink.rs
wireguard-broker/src/lib.rs

This PR, majority of the contributions by @aminfa, adds tests, documentation and examples to the wireguard-broker crate.

docs(wireguard-broker): add docs and examples

---

util/src/mio/uds_send_fd.rs

Add a docstring example for mio/uds_send_fd

---

constant-time/src/memcmp.rs

9bae080c4de3809ecbb87035305d5d64993ec403
Co-Authored-By: @phildremi

fix: Accidental removed line of comment

---

.github/workflows/docker.yaml

* Multi platform support is broken right now, fix it
* Cleanup use of unnecessary role

Docker CI multi platform fix and cleanup

---

.github/workflows/cargo-crev-exemptions-dependabot.yml

Merge PR for #630 (rebase needed)

ci(supply-chain+dependabot): Automatically create exemptions for cargo-crev for dependa-bot PRs

---

.github/workflows/bench-primitives.yml
.github/workflows/bench-protocol.yml
Cargo.lock
Cargo.toml
ciphers/Cargo.toml
ciphers/benches/primitives.rs
ciphers/src/subtle/libcrux/mod.rs
ciphers/src/subtle/mod.rs
flake.nix
pkgs/rosenpass.nix
readme.md
rosenpass/Cargo.toml
rosenpass/benches/trace_handshake.rs
rosenpass/src/protocol/protocol.rs
util/Cargo.toml
util/src/lib.rs
util/src/trace_bench.rs

Benchmarks (CI Run)
